### ISSUE TITLE
Interface programu

### ISSUE THREAD

**Issue by krykol** [Uchoslyszy/okowidzi#5]
Interfejs:
1. Okienko, nie konsola
2. Buttony - wczytywanie obrazu, rodzaj przeróbki (funkcje dostaniemy później, na razie same templaty) 
3. Dwa widoki obrazka - przed i po
4.  zrobienie miejsca pod histogramy przed i po - OSOBNE OKIENKO = ŁATWIEJSZY KOD

**Comment by Uchoslyszy** [comment]
Interface śliczny, klient zadowolony :)
